// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webAPI.Data;

#nullable disable

namespace webAPI.Data.Migrations
{
    [DbContext(typeof(webAPIDbContext))]
    [Migration("20231209030551_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("webApi.Data.Models.ActivityDataModel", b =>
                {
                    b.Property<int>("ActivityDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityDataId"));

                    b.Property<float>("DailyDistance")
                        .HasColumnType("real");

                    b.Property<float>("DailyEnergyBurned")
                        .HasColumnType("real");

                    b.Property<int>("DailySteps")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Workouts")
                        .HasColumnType("int");

                    b.HasKey("ActivityDataId");

                    b.HasIndex("UserId");

                    b.ToTable("ActivityDataModels");
                });

            modelBuilder.Entity("webApi.Data.Models.ActivityRecommendationModel", b =>
                {
                    b.Property<int>("ActivityRecommendationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityRecommendationId"));

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ActivityRecommendationId");

                    b.HasIndex("UserId");

                    b.ToTable("ActivityRecommendationModels");
                });

            modelBuilder.Entity("webApi.Data.Models.HealthDataModel", b =>
                {
                    b.Property<int>("HealthDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HealthDataId"));

                    b.Property<float>("Bmi")
                        .HasColumnType("real")
                        .HasColumnName("BMI");

                    b.Property<float>("BodyFat")
                        .HasColumnType("real");

                    b.Property<float>("BodyMass")
                        .HasColumnType("real");

                    b.Property<float>("LeanBodyMass")
                        .HasColumnType("real");

                    b.Property<string>("SleepAnalysis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("HealthDataId");

                    b.HasIndex("UserId");

                    b.ToTable("HealthDataModels");
                });

            modelBuilder.Entity("webApi.Data.Models.HealthRecommendationModel", b =>
                {
                    b.Property<int>("HealthRecommendationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HealthRecommendationId"));

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("HealthRecommendationId");

                    b.HasIndex("UserId");

                    b.ToTable("HealthRecommendationModels");
                });

            modelBuilder.Entity("webApi.Data.Models.UserModel", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("UserModels");
                });

            modelBuilder.Entity("webApi.Data.Models.ActivityDataModel", b =>
                {
                    b.HasOne("webApi.Data.Models.UserModel", "User")
                        .WithMany("ActivityDataModels")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("webApi.Data.Models.ActivityRecommendationModel", b =>
                {
                    b.HasOne("webApi.Data.Models.UserModel", "User")
                        .WithMany("ActivityRecommendationModels")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("webApi.Data.Models.HealthDataModel", b =>
                {
                    b.HasOne("webApi.Data.Models.UserModel", "User")
                        .WithMany("HealthDataModels")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("webApi.Data.Models.HealthRecommendationModel", b =>
                {
                    b.HasOne("webApi.Data.Models.UserModel", "User")
                        .WithMany("HealthRecommendationModels")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("webApi.Data.Models.UserModel", b =>
                {
                    b.Navigation("ActivityDataModels");

                    b.Navigation("ActivityRecommendationModels");

                    b.Navigation("HealthDataModels");

                    b.Navigation("HealthRecommendationModels");
                });
#pragma warning restore 612, 618
        }
    }
}
